### ISSUE TITLE
App crashes when I try to create a folder (Ubuntu 22.04.2)

### ISSUE THREAD

**Issue by axiomtutor** [yonatanmgr/mathberet#15]
**Describe the bug**
When I run the app I get a `libva` error message.  The app still opens, though, and when I try to create a folder, the app crashes.

**To Reproduce**
1. In a terminal pointed to the install directory, run `npm start`.
2. When the app opens, click the notepad icon and the new folder icon.

**Expected behavior**
New folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/27108390/226429418-4ecf3474-465e-4a6f-ae0b-6b0fb126f63d.png)
![image](https://user-images.githubusercontent.com/27108390/226429541-30800cb1-97f1-40df-ab27-5873e418052f.png)
![image](https://user-images.githubusercontent.com/27108390/226429582-a8a6f17c-a4e7-4f70-bd51-6f2f1de27734.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2

**Additional context**
I installed `npm` in order to install this application, but believe I have a correct installation of `npm` version 9.5.0 and `node` version v18.15.0.  I could be wrong, I'm not very familiar with these packages, so I can try out any terminal commands that might be helpful, but these print out the version numbers that I've shown here with `npm --version` and `node --version`.  

I tried installing `libva` either through `npm` or `apt-get` and neither could find the package.

**Comment by yonatanmgr** [comment]
Hey @axiomtutor, good to have you here!

Although we're not familiar with the `libva` error, we're currently trying to reproduce it on a similar environment. Will update on this matter.

About the folder/file creating folder - we are familiar with it (see #4). A workaround is to first create a file/folder manually and then start working. Thus, in the last commit, I've made it so the files directory is created with an initial file (that should also serve as an onboarding file). Try pulling from the repository again and deleting `~/Documents/Mathberet`, running `npm start` again.

**Comment by axiomtutor** [comment]
Gotcha, that's no problem. I look forward to seeing how this develops!
